apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend-proxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://sykmeldinger-backend-proxy.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  accessPolicy:
    outbound:
      external:
        - host: api-gw.oera.no 
      rules:
        - application: sykmeldinger-backend
  envFrom:
    - secret: sykmeldinger-backend-proxy-p-apigw-key # Will expose SERVICE_GATEWAY_KEY inside the pod
  env:
    - name: ALLOWED_ORIGINS
      value: "https://tjenester.nav.no,https://www.nav.no"
    - name: SERVICE_GATEWAY_URL
      value: https://api-gw.oera.no/sykmeldinger-backend
