apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-backend-proxy
  namespace: teamsykmelding
 labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://sykmeldinger-backend-proxy.dev.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 90
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 90
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 768Mi
  accessPolicy:
    outbound:
      external:
        - host: api-gw-q1.oera.no 
      rules:
        - application: sykmeldinger-backend
  envFrom:
    - secret: sykmeldinger-backend-proxy-q1-apigw-key # Will expose SERVICE_GATEWAY_KEY inside the pod
  env:
    - name: ALLOWED_ORIGINS
      value: "https://tjenester-q1.nav.no,https://www-gcp.dev.nav.no,https://flex-vedtak-mock.dev.nav.no"
    - name: SERVICE_GATEWAY_URL
      value: https://api-gw-q1.oera.no/sykmeldinger-backend
