GET:
  - api/v1/sykmeldinger
  - api/v1/syforest/sykmeldinger
POST:
  - api/v1/sykmeldinger/{sykmeldingId}/bekreft
  - sykmeldinger/{sykmeldingId}/status
  - sykmeldinger/{sykmeldingId}/bekreft
  - sykmeldinger/{sykmeldingId}/send
