get:
    - api/v1/sykmeldinger
    - api/v1/sykmeldinger/{sykmeldingId}
    - api/v1/syforest/sykmeldinger
    - api/v1/syforest/arbeidsforhold
    - api/v1/syforest/brukerinformasjon
post:
    - api/v1/sykmeldinger/{sykmeldingId}/bekreft
    - api/v1/sykmeldinger/{sykmeldingId}/avbryt
    - api/v1/sykmeldinger/{sykmeldingId}/gjenapne
    - api/v1/sykmeldinger/{sykmeldingId}/send
